//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SakaryaBufe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manset
    {
        public int id { get; set; }
        public string Mbaslik { get; set; }
        public string Maciklama { get; set; }
        public string MresimYol { get; set; }
    }
}
