//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SakaryaBufe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        public int id { get; set; }
        public string Baslik { get; set; }
        public string Aciklama { get; set; }
        public string ResimYol { get; set; }
        public string Fiyat { get; set; }
        public Nullable<int> Kategori { get; set; }
    
        public virtual Resimler Resimler { get; set; }
        public virtual Kategori Kategori1 { get; set; }
    }
}
